pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "dockerhubuser/cicd-app"
        DOCKER_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Build Docker Image') {
            steps {
                sh '''
                  docker build -t $DOCKER_IMAGE:$DOCKER_TAG -f cicd/Dockerfile cicd
                '''
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                      docker push $DOCKER_IMAGE:$DOCKER_TAG
                    '''
                }
            }
        }

        stage('Deploy to Minikube') {
            steps {
                sh '''
                  sed -i "s|IMAGE_PLACEHOLDER|$DOCKER_IMAGE:$DOCKER_TAG|g" cicd/deployment.yaml
                  kubectl apply -f cicd/deployment.yaml
                  kubectl apply -f cicd/service.yaml
                '''
            }
        }
    }
}
